// This file is auto-generated by @hey-api/openapi-ts

export const Body_images_upload_imageSchema = {
    properties: {
        file: {
            type: 'string',
            contentMediaType: 'application/octet-stream',
            title: 'File'
        }
    },
    type: 'object',
    required: ['file'],
    title: 'Body_images-upload_image'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ImageCategoriesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ImageCategoryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ImageCategoriesPublic',
    description: '分类列表响应'
} as const;

export const ImageCategoryCreateSchema = {
    properties: {
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: '描述'
        },
        sort_order: {
            type: 'integer',
            title: '排序权重',
            default: 0
        },
        icon: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: '图标名称'
        },
        name: {
            type: 'string',
            maxLength: 32,
            minLength: 1,
            title: '分类标识',
            description: '小写英文字母开头，仅允许小写字母、数字、下划线'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ImageCategoryCreate',
    description: '创建分类请求'
} as const;

export const ImageCategoryPublicSchema = {
    properties: {
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: '描述'
        },
        sort_order: {
            type: 'integer',
            title: '排序权重',
            default: 0
        },
        icon: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: '图标名称'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        image_count: {
            type: 'integer',
            title: 'Image Count'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'is_active', 'image_count'],
    title: 'ImageCategoryPublic',
    description: '分类公开响应'
} as const;

export const ImageCategoryUpdateSchema = {
    properties: {
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: '描述'
        },
        sort_order: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: '排序权重'
        },
        icon: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: '图标名称'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: '激活状态'
        }
    },
    type: 'object',
    title: 'ImageCategoryUpdate',
    description: '更新分类请求（全部可选）'
} as const;

export const ImagePublicSchema = {
    properties: {
        filename: {
            type: 'string',
            maxLength: 255,
            title: 'Filename'
        },
        file_size: {
            type: 'integer',
            title: 'File Size'
        },
        width: {
            type: 'integer',
            title: 'Width'
        },
        height: {
            type: 'integer',
            title: 'Height'
        },
        category: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: '分类'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        url: {
            type: 'string',
            title: 'Url'
        }
    },
    type: 'object',
    required: ['filename', 'file_size', 'width', 'height', 'id', 'owner_id', 'url'],
    title: 'ImagePublic',
    description: '图片公开响应'
} as const;

export const ImageUpdateSchema = {
    properties: {
        category: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: '分类'
        }
    },
    type: 'object',
    title: 'ImageUpdate',
    description: '更新图片请求'
} as const;

export const ImagesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ImagePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ImagesPublic',
    description: '图片列表响应'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate',
    description: '创建物品请求'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            format: 'uuid',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        image_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Id'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic',
    description: '物品公开响应'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        image_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: '配图图片 ID'
        }
    },
    type: 'object',
    title: 'ItemUpdate',
    description: '更新物品请求（全部可选）'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic',
    description: '物品列表响应'
} as const;

export const LevelPublicSchema = {
    properties: {
        level: {
            type: 'integer',
            maximum: 10,
            minimum: 1,
            title: '等级编号',
            description: '等级编号，范围 1～10，固定不可修改'
        },
        name: {
            type: 'string',
            maxLength: 255,
            title: '等级名称',
            description: '等级名称，如「练气期」'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: '等级描述'
        },
        is_default: {
            type: 'boolean',
            title: '是否默认',
            description: '是否为新用户的默认等级',
            default: false
        },
        id: {
            type: 'string',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['level', 'name', 'id'],
    title: 'LevelPublic',
    description: '等级公开响应'
} as const;

export const LevelUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: '等级名称'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: '等级描述'
        },
        is_default: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: '是否默认'
        }
    },
    type: 'object',
    title: 'LevelUpdate',
    description: '更新等级请求（全部可选）'
} as const;

export const LevelsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/LevelPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'LevelsPublic',
    description: '等级列表响应'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message',
    description: '通用响应消息'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword',
    description: '重置密码请求'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate',
    description: '内部创建用户请求（仅管理员接口使用）'
} as const;

export const SupplierBalancePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        balance: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Balance'
        },
        message: {
            type: 'string',
            title: 'Message',
            default: '余额已同步'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'SupplierBalancePublic',
    description: '余额同步响应'
} as const;

export const SupplierCreateSchema = {
    properties: {
        platform: {
            type: 'string',
            maxLength: 64,
            title: '平台',
            description: '供应商平台标识，如 openai、azure、deepseek'
        },
        name: {
            type: 'string',
            maxLength: 255,
            title: '供应商名称',
            description: '供应商名称标识'
        },
        base_url: {
            type: 'string',
            maxLength: 512,
            title: 'API 基础地址',
            description: 'API 请求的基础 URL'
        },
        app_key: {
            type: 'string',
            maxLength: 512,
            title: '应用密钥 Key',
            description: 'API 认证密钥 Key'
        },
        app_secret: {
            type: 'string',
            maxLength: 512,
            title: '应用密钥 Secret',
            description: 'API 认证密钥 Secret，响应中脱敏'
        },
        status: {
            type: 'string',
            maxLength: 32,
            title: '状态',
            description: 'active=启用中, inactive=已停用, suspended=异常冻结',
            default: 'active'
        },
        connection_status: {
            type: 'string',
            maxLength: 32,
            title: '连接状态',
            description: 'online=可达, offline=不可达, unknown=未知',
            default: 'unknown'
        },
        timeout_seconds: {
            type: 'integer',
            maximum: 300,
            minimum: 1,
            title: '超时秒数',
            description: 'API 请求超时时间',
            default: 30
        },
        retry_times: {
            type: 'integer',
            maximum: 10,
            minimum: 0,
            title: '重试次数',
            description: '请求失败时的重试次数',
            default: 3
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: '描述',
            description: '备注说明'
        }
    },
    type: 'object',
    required: ['platform', 'name', 'base_url', 'app_key', 'app_secret'],
    title: 'SupplierCreate',
    description: '创建供应商请求'
} as const;

export const SupplierPublicSchema = {
    properties: {
        platform: {
            type: 'string',
            maxLength: 64,
            title: '平台',
            description: '供应商平台标识，如 openai、azure、deepseek'
        },
        name: {
            type: 'string',
            maxLength: 255,
            title: '供应商名称',
            description: '供应商名称标识'
        },
        base_url: {
            type: 'string',
            maxLength: 512,
            title: 'API 基础地址',
            description: 'API 请求的基础 URL'
        },
        app_key: {
            type: 'string',
            maxLength: 512,
            title: '应用密钥 Key',
            description: 'API 认证密钥 Key'
        },
        app_secret: {
            type: 'string',
            maxLength: 512,
            title: '应用密钥 Secret',
            description: 'API 认证密钥 Secret，响应中脱敏'
        },
        status: {
            type: 'string',
            maxLength: 32,
            title: '状态',
            description: 'active=启用中, inactive=已停用, suspended=异常冻结',
            default: 'active'
        },
        connection_status: {
            type: 'string',
            maxLength: 32,
            title: '连接状态',
            description: 'online=可达, offline=不可达, unknown=未知',
            default: 'unknown'
        },
        timeout_seconds: {
            type: 'integer',
            maximum: 300,
            minimum: 1,
            title: '超时秒数',
            description: 'API 请求超时时间',
            default: 30
        },
        retry_times: {
            type: 'integer',
            maximum: 10,
            minimum: 0,
            title: '重试次数',
            description: '请求失败时的重试次数',
            default: 3
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: '描述',
            description: '备注说明'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        balance: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Balance'
        }
    },
    type: 'object',
    required: ['platform', 'name', 'base_url', 'app_key', 'app_secret', 'id'],
    title: 'SupplierPublic',
    description: '供应商公开响应'
} as const;

export const SupplierUpdateSchema = {
    properties: {
        platform: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64
                },
                {
                    type: 'null'
                }
            ],
            title: 'Platform'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        base_url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512
                },
                {
                    type: 'null'
                }
            ],
            title: 'Base Url'
        },
        app_key: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512
                },
                {
                    type: 'null'
                }
            ],
            title: 'App Key'
        },
        app_secret: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 512
                },
                {
                    type: 'null'
                }
            ],
            title: 'App Secret'
        },
        status: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        connection_status: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Connection Status'
        },
        timeout_seconds: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 300,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Timeout Seconds'
        },
        retry_times: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 10,
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Retry Times'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1024
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'SupplierUpdate',
    description: '更新供应商请求（全部可选，不含 balance）'
} as const;

export const SuppliersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/SupplierPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'SuppliersPublic',
    description: '供应商列表响应'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token',
    description: '访问令牌响应'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword',
    description: '修改密码请求'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate',
    description: '创建用户请求'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic',
    description: '用户公开响应'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister',
    description: '用户注册请求'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate',
    description: '更新用户请求（全部可选）'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe',
    description: '当前用户更新个人信息请求'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic',
    description: '用户列表响应'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;