// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ImagesReadImagesData, ImagesReadImagesResponse, ImagesReadImageData, ImagesReadImageResponse, ImagesDeleteImageData, ImagesDeleteImageResponse, ImagesUploadImageData, ImagesUploadImageResponse, ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserPrivateData, PrivateCreateUserPrivateResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse, ImageCategoriesReadCategoriesResponse, ImageCategoriesReadCategoryData, ImageCategoriesReadCategoryResponse, ImageCategoriesCreateCategoryData, ImageCategoriesCreateCategoryResponse, ImageCategoriesUpdateCategoryData, ImageCategoriesUpdateCategoryResponse, ImageCategoriesDeleteCategoryData, ImageCategoriesDeleteCategoryResponse, ImagesUpdateImageData, ImagesUpdateImageResponse } from './types.gen';

export class ImagesService {
    /**
     * Read Images
     * 鑾峰彇褰撳墠鐢ㄦ埛鐨勫浘鐗囧垪琛?
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @param data.category
     * @returns ImagesPublic Successful Response
     * @throws ApiError
     */
    public static readImages(data: ImagesReadImagesData = {}): CancelablePromise<ImagesReadImagesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/images/',
            query: {
                skip: data.skip,
                limit: data.limit,
                category: data.category
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Category Options
     * 鑾峰彇鍒嗙被閫夐」鍒楄〃锛堜粎 name + label锛屼緵涓婁紶琛ㄥ崟浣跨敤锛?
     * @returns string[] Successful Response
     * @throws ApiError
     */
    public static readCategoryOptions(): CancelablePromise<Array<string>> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/image-categories/options',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Image

    /**
     * Read Categories
     * 获取所有图片分类列表（含图片计数）
     * @returns ImageCategoriesPublic Successful Response
     * @throws ApiError
     */
    public static readCategories(): CancelablePromise<ImageCategoriesReadCategoriesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/image-categories/',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Read Category
     * 根据 ID 获取分类详情
     * @param data The data for the request.
     * @param data.id
     * @returns ImageCategoryPublic Successful Response
     * @throws ApiError
     */
    public static readCategory(data: ImageCategoriesReadCategoryData): CancelablePromise<ImageCategoriesReadCategoryResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/image-categories/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Create Category
     * 创建图片分类（管理员）
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ImageCategoryPublic Successful Response
     * @throws ApiError
     */
    public static createCategory(data: ImageCategoriesCreateCategoryData): CancelablePromise<ImageCategoriesCreateCategoryResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/image-categories/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Update Category
     * 更新图片分类（管理员）
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ImageCategoryPublic Successful Response
     * @throws ApiError
     */
    public static updateCategory(data: ImageCategoriesUpdateCategoryData): CancelablePromise<ImageCategoriesUpdateCategoryResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/image-categories/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Delete Category
     * 删除图片分类（管理员），有图片引用时拒绝删除
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteCategory(data: ImageCategoriesDeleteCategoryData): CancelablePromise<ImageCategoriesDeleteCategoryResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/image-categories/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    /**
     * 鏍规嵁 ID 鑾峰彇鍥剧墖鍏冩暟鎹?
     * @param data The data for the request.
     * @param data.id
     * @returns ImagePublic Successful Response
     * @throws ApiError
     */
    public static readImage(data: ImagesReadImageData): CancelablePromise<ImagesReadImageResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/images/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Image
     * 鍒犻櫎鍥剧墖锛堝悓鏃跺垹闄ょ鐩樻枃浠讹級
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteImage(data: ImagesDeleteImageData): CancelablePromise<ImagesDeleteImageResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/images/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Upload Image
     * 涓婁紶鍥剧墖锛屾敮鎸?JPEG/PNG/WebP锛岃嚜鍔ㄥ帇缂╀负 WebP 缂╃暐鍥?
     * @param data The data for the request.
     * @param data.formData
     * @returns ImagePublic Successful Response
     * @throws ApiError
     */
    public static uploadImage(data: ImagesUploadImageData): CancelablePromise<ImagesUploadImageResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/images/upload',
            formData: data.formData,
            mediaType: 'multipart/form-data',
            query: {
                category: data.category
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    /**
     * Update Image
     * Update image category
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ImagePublic Successful Response
     * @throws ApiError
     */
    public static updateImage(data: ImagesUpdateImageData): CancelablePromise<ImagesUpdateImageResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/images/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}
export class ItemsService {
    /**
     * Read Items
     * 鑾峰彇鐗╁搧鍒楄〃
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Item
     * 鍒涘缓鏂扮墿鍝?
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Item
     * 鏍规嵁 ID 鑾峰彇鐗╁搧
     * @param data The data for the request.
     * @param data.id
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Item
     * 鏇存柊鐗╁搧锛堟敮鎸佽缃?鍙栨秷閰嶅浘锛?
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Item
     * 鍒犻櫎鐗╁搧
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 鍏煎鐨勭櫥褰曟帴鍙ｏ紝鑾峰彇璁块棶浠ょ墝
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * 娴嬭瘯璁块棶浠ょ墝鏄惁鏈夋晥
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * 瀵嗙爜鎵惧洖鈥斺€斿彂閫侀噸缃摼鎺ラ偖浠?
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * 閲嶇疆瀵嗙爜
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * 鑾峰彇瀵嗙爜鎵惧洖閭欢鐨?HTML 鍐呭锛堜粎瓒呯骇绠＄悊鍛樺彲鐢級
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User Private
     * 鍐呴儴鎺ュ彛锛氬垱寤烘柊鐢ㄦ埛锛堜粎寮€鍙戠幆澧冨彲鐢級
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUserPrivate(data: PrivateCreateUserPrivateData): CancelablePromise<PrivateCreateUserPrivateResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * 鑾峰彇鐢ㄦ埛鍒楄〃锛堜粎瓒呯骇绠＄悊鍛樺彲鐢級
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * 鍒涘缓鏂扮敤鎴凤紙浠呰秴绾х鐞嗗憳鍙敤锛?
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * 鑾峰彇褰撳墠鐢ㄦ埛淇℃伅
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * 鍒犻櫎褰撳墠鐢ㄦ埛锛堣秴绾х鐞嗗憳涓嶅厑璁稿垹闄よ嚜宸憋級
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * 鏇存柊褰撳墠鐢ㄦ埛涓汉淇℃伅
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * 淇敼褰撳墠鐢ㄦ埛瀵嗙爜
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * 鐢ㄦ埛鑷姪娉ㄥ唽
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * 鏍规嵁 ID 鑾峰彇鐢ㄦ埛
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * 鏇存柊鐢ㄦ埛淇℃伅锛堜粎瓒呯骇绠＄悊鍛樺彲鐢級
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * 鍒犻櫎鐢ㄦ埛锛堜粎瓒呯骇绠＄悊鍛樺彲鐢紝涓嶅厑璁稿垹闄よ嚜宸憋級
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * 鍙戦€佹祴璇曢偖浠讹紙浠呰秴绾х鐞嗗憳鍙敤锛?
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * 鍋ュ悍妫€鏌?
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}


