// This file is auto-generated by @hey-api/openapi-ts

/**
 * 管理员下单结算预览商品行
 */
export type AdminOrderPreviewItem = {
    /**
     * 从 1 开始
     */
    index: number;
    product_id: string;
    product_name: string;
    quantity: number;
    unit_price: string;
    subtotal: string;
};

/**
 * 管理员下单单张订单结果
 */
export type AdminOrderResult = {
    /**
     * 从 1 开始
     */
    index: number;
    success: boolean;
    order?: (OrderPublic | null);
    detail?: (string | null);
};

/**
 * 管理员批量下单请求
 */
export type AdminOrdersCreate = {
    /**
     * 每张订单独立创建，单张失败不影响其他订单
     */
    orders: Array<OrderCreate>;
};

/**
 * 管理员下单结算预览响应
 */
export type AdminOrdersPreviewPublic = {
    total: number;
    total_amount: string;
    items?: Array<AdminOrderPreviewItem>;
};

/**
 * 管理员批量下单响应
 */
export type AdminOrdersPublic = {
    total: number;
    success_count: number;
    failure_count: number;
    results: Array<AdminOrderResult>;
};

/**
 * 发布业务事件请求
 */
export type AutomationEventCreate = {
    /**
     * 如 order.paid
     */
    event_type: string;
    payload?: {
        [key: string]: unknown;
    };
};

/**
 * 自动化事件公开响应
 */
export type AutomationEventPublic = {
    id: string;
    event_type: string;
    payload: {
        [key: string]: unknown;
    };
    created_at: (string | null);
};

/**
 * 自动化事件列表响应
 */
export type AutomationEventsPublic = {
    data: Array<AutomationEventPublic>;
    count: number;
};

/**
 * 创建自动化规则请求
 */
export type AutomationRuleCreate = {
    /**
     * 监听的业务事件类型
     */
    event_type: string;
    /**
     * 对应已注册 Executor 的任务类型
     */
    action_type: string;
    /**
     * 合并进任务 payload，可覆盖事件载荷中的同名参数
     */
    config?: {
        [key: string]: unknown;
    };
    is_active?: boolean;
};

/**
 * 自动化规则公开响应
 */
export type AutomationRulePublic = {
    id: string;
    event_type: string;
    action_type: string;
    config: {
        [key: string]: unknown;
    };
    is_active: boolean;
    created_at: (string | null);
    updated_at: (string | null);
};

/**
 * 自动化规则列表响应
 */
export type AutomationRulesPublic = {
    data: Array<AutomationRulePublic>;
    count: number;
};

/**
 * 更新自动化规则请求（全部可选）
 */
export type AutomationRuleUpdate = {
    event_type?: (string | null);
    action_type?: (string | null);
    config?: ({
    [key: string]: unknown;
} | null);
    is_active?: (boolean | null);
};

/**
 * 自动化任务归档公开响应
 */
export type AutomationTaskArchivePublic = {
    id: string;
    task_type: string;
    status: AutomationTaskStatus;
    priority: number;
    execute_at: string;
    retry_count: number;
    max_retry: number;
    payload: {
        [key: string]: unknown;
    };
    error_message: (string | null);
    finished_at: (string | null);
    created_at: (string | null);
    updated_at: (string | null);
    archived_at: string;
};

/**
 * 自动化任务归档列表响应
 */
export type AutomationTaskArchivesPublic = {
    data: Array<AutomationTaskArchivePublic>;
    count: number;
};

/**
 * 创建自动化任务请求
 */
export type AutomationTaskCreate = {
    /**
     * 对应已注册 Executor 的任务类型
     */
    task_type: string;
    /**
     * 执行所需参数
     */
    payload?: {
        [key: string]: unknown;
    };
    /**
     * 数值越大越优先执行
     */
    priority?: number;
    /**
     * 为空则立即执行
     */
    execute_at?: (string | null);
    max_retry?: number;
};

/**
 * 自动化任务公开响应
 */
export type AutomationTaskPublic = {
    id: string;
    task_type: string;
    status: AutomationTaskStatus;
    priority: number;
    execute_at: string;
    retry_count: number;
    max_retry: number;
    payload: {
        [key: string]: unknown;
    };
    error_message: (string | null);
    finished_at: (string | null);
    created_at: (string | null);
    updated_at: (string | null);
};

/**
 * 自动化任务列表响应
 */
export type AutomationTasksPublic = {
    data: Array<AutomationTaskPublic>;
    count: number;
};

/**
 * 自动化任务状态
 */
export type AutomationTaskStatus = 'pending' | 'running' | 'success' | 'failed' | 'canceled';

/**
 * 供应商上游实时余额响应
 */
export type BalancePublic = {
    /**
     * 上游账户实时余额
     */
    balance: (string | null);
};

export type Body_images_upload_image = {
    file: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * crontab 表达式输入
 */
export type CrontabScheduleIn = {
    minute?: string;
    hour?: string;
    day_of_week?: string;
    day_of_month?: string;
    month_of_year?: string;
    timezone?: string;
};

/**
 * crontab 配置响应
 */
export type CrontabSchedulePublic = {
    minute?: string;
    hour?: string;
    day_of_week?: string;
    day_of_month?: string;
    month_of_year?: string;
    timezone?: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * 分类列表响应
 */
export type ImageCategoriesPublic = {
    data: Array<ImageCategoryPublic>;
    count: number;
};

/**
 * 创建分类请求
 */
export type ImageCategoryCreate = {
    description?: (string | null);
    sort_order?: number;
    icon?: (string | null);
    /**
     * 小写英文字母开头，仅允许小写字母、数字、下划线
     */
    name: string;
};

/**
 * 分类公开响应
 */
export type ImageCategoryPublic = {
    description?: (string | null);
    sort_order?: number;
    icon?: (string | null);
    id: string;
    name: string;
    is_active: boolean;
    image_count: number;
    created_at?: (string | null);
};

/**
 * 更新分类请求（全部可选）
 */
export type ImageCategoryUpdate = {
    description?: (string | null);
    sort_order?: (number | null);
    icon?: (string | null);
    is_active?: (boolean | null);
};

/**
 * 图片公开响应
 */
export type ImagePublic = {
    filename: string;
    file_size: number;
    width: number;
    height: number;
    category?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
    url: string;
};

/**
 * 图片列表响应
 */
export type ImagesPublic = {
    data: Array<ImagePublic>;
    count: number;
};

/**
 * 更新图片请求
 */
export type ImageUpdate = {
    category?: (string | null);
};

/**
 * 下单参数输入类型
 */
export type InputType = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15;

/**
 * Interval 周期单位
 */
export type IntervalPeriod = 'days' | 'hours' | 'minutes' | 'seconds' | 'microseconds';

/**
 * interval 间隔输入
 */
export type IntervalScheduleIn = {
    every?: number;
    /**
     * days/hours/minutes/seconds/microseconds
     */
    period?: IntervalPeriod;
};

/**
 * interval 配置响应
 */
export type IntervalSchedulePublic = {
    every?: number;
    /**
     * days/hours/minutes/seconds/microseconds
     */
    period?: IntervalPeriod;
};

/**
 * 创建物品请求
 */
export type ItemCreate = {
    title: string;
    description?: (string | null);
};

/**
 * 物品公开响应
 */
export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
    image_id?: (string | null);
    image_url?: (string | null);
};

/**
 * 物品列表响应
 */
export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

/**
 * 更新物品请求（全部可选）
 */
export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
    image_id?: (string | null);
};

/**
 * 等级公开响应
 */
export type LevelPublic = {
    /**
     * 等级编号，范围 1～10，固定不可修改
     */
    level: number;
    /**
     * 等级名称，如「练气期」
     */
    name: string;
    description?: (string | null);
    /**
     * 是否为新用户的默认等级
     */
    is_default?: boolean;
    id: string;
};

/**
 * 等级列表响应
 */
export type LevelsPublic = {
    data: Array<LevelPublic>;
    count: number;
};

/**
 * 更新等级请求（全部可选）
 */
export type LevelUpdate = {
    name?: (string | null);
    description?: (string | null);
    is_default?: (boolean | null);
};

/**
 * 通用响应消息
 */
export type Message = {
    message: string;
};

/**
 * 重置密码请求
 */
export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * 创建订单请求
 */
export type OrderCreate = {
    product_id: string;
    quantity: number;
    /**
     * 按商品购买参数 key 传值
     */
    params?: ({
    [key: string]: unknown;
} | null);
    remark?: (string | null);
};

/**
 * 订单列表响应，仅返回列表所需字段
 */
export type OrderListItem = {
    id: string;
    /**
     * 下单用户的用户名，管理员接口返回
     */
    username?: (string | null);
    status: OrderStatus;
    total_amount: string;
    product_name: string;
    quantity: number;
    params: {
        [key: string]: unknown;
    };
    created_at?: (string | null);
};

/**
 * 订单响应
 */
export type OrderPublic = {
    id: string;
    order_no: string;
    user_id: string;
    /**
     * 下单用户的用户名，管理员接口返回
     */
    username?: (string | null);
    status: OrderStatus;
    total_amount: string;
    currency: string;
    remark?: (string | null);
    paid_at?: (string | null);
    processing_at?: (string | null);
    completed_at?: (string | null);
    canceled_at?: (string | null);
    refunded_at?: (string | null);
    failed_at?: (string | null);
    fulfill_failed_count?: number;
    created_at?: (string | null);
    updated_at?: (string | null);
    product_id: (string | null);
    product_name: string;
    quantity: number;
    start_quantity: number;
    current_quantity: number;
    unit_price: string;
    subtotal: string;
    base_price: string;
    cost_price: string;
    loss_price: string;
    params: {
        [key: string]: unknown;
    };
    fulfillment_type: RedeemType;
    supplier_order_id?: (string | null);
    supplier_id?: (string | null);
    sku_id?: (string | null);
    can_refund: boolean;
};

/**
 * 管理员手动退款请求
 */
export type OrderRefundRequest = {
    /**
     * 退款金额不能超过订单金额
     */
    amount: (number | string);
};

/**
 * 订单列表响应
 */
export type OrdersPublic = {
    data: Array<OrderListItem>;
    count: number;
};

/**
 * 订单状态（与上游一致）
 */
export type OrderStatus = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10;

/**
 * 管理员设置订单状态请求
 */
export type OrderStatusUpdateRequest = {
    status: OrderStatus;
};

/**
 * 供应商平台枚举
 */
export type PlatformEnum = 'self' | 'ylsup';

/**
 * 平台选项——供前端下拉菜单使用
 */
export type PlatformOption = {
    /**
     * 枚举值，用于表单提交
     */
    value: string;
    /**
     * 展示名称，用于下拉菜单展示
     */
    label: string;
};

/**
 * 平台选项列表响应
 */
export type PlatformOptionsPublic = {
    data: Array<PlatformOption>;
};

/**
 * 创建价格模板请求；未传的等级自动按 15 折补齐
 */
export type PriceTemplateCreate = {
    /**
     * 价格模板名称，全局唯一
     */
    name: string;
    /**
     * 创建商品未选择模板时默认使用的模板，仅允许一个为 True
     */
    is_default?: boolean;
    description?: (string | null);
    /**
     * 1-10 等级折扣，未设置等级的折扣按 15 折（1.5000）
     */
    rules?: Array<PriceTemplateRuleIn>;
};

/**
 * 价格模板公开响应
 */
export type PriceTemplatePublic = {
    id: string;
    name: string;
    description: (string | null);
    is_default: boolean;
    is_active: boolean;
    created_at: (string | null);
    updated_at: (string | null);
    rules: Array<PriceTemplateRulePublic>;
};

/**
 * 设置单个等级折扣请求
 */
export type PriceTemplateRuleIn = {
    /**
     * 用户等级编号 1-10
     */
    level: number;
    /**
     * 实际价格 = 商品基准价 × 折扣率；15 折为 1.5000
     */
    discount_rate?: (number | string);
};

/**
 * 价格模板等级折扣响应
 */
export type PriceTemplateRulePublic = {
    id: string;
    level: number;
    discount_rate: string;
};

/**
 * 价格模板列表响应
 */
export type PriceTemplatesPublic = {
    data: Array<PriceTemplatePublic>;
    count: number;
};

/**
 * 更新价格模板请求（全部可选）；rules 只覆盖传入等级，其余等级保留
 */
export type PriceTemplateUpdate = {
    name?: (string | null);
    description?: (string | null);
    is_active?: (boolean | null);
    is_default?: (boolean | null);
    /**
     * 传入的等级折扣将被覆盖，未传入等级保留原折扣
     */
    rules?: (Array<PriceTemplateRuleIn> | null);
};

/**
 * 内部创建用户请求（仅管理员接口使用）
 */
export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * 商品下单参数创建请求
 */
export type ProductBuyParamCreate = {
    /**
     * 参数键，同一商品内唯一
     */
    key: string;
    label: string;
    value?: string;
    description?: string;
    input_type?: InputType;
    type_config?: Array<{
        [key: string]: unknown;
    }>;
    default_value?: string;
    use_default?: boolean;
    is_required?: boolean;
    is_hidden?: boolean;
    is_edit?: boolean;
    validate_min?: number;
    validate_max?: number;
};

/**
 * 商品下单参数公开响应
 */
export type ProductBuyParamPublic = {
    id: string;
    key: string;
    label: string;
    value: string;
    description: string;
    input_type: InputType;
    type_config: Array<{
        [key: string]: unknown;
    }>;
    default_value: string;
    use_default: boolean;
    is_required: boolean;
    is_hidden: boolean;
    is_edit: boolean;
    validate_min: number;
    validate_max: number;
};

/**
 * 商品下单参数更新请求（全部可选）
 */
export type ProductBuyParamUpdate = {
    key?: (string | null);
    label?: (string | null);
    value?: (string | null);
    description?: (string | null);
    input_type?: (InputType | null);
    type_config?: (Array<{
    [key: string]: unknown;
}> | null);
    default_value?: (string | null);
    use_default?: (boolean | null);
    is_required?: (boolean | null);
    is_hidden?: (boolean | null);
    is_edit?: (boolean | null);
    validate_min?: (number | null);
    validate_max?: (number | null);
};

/**
 * 商品分类列表响应
 */
export type ProductCategoriesPublic = {
    data: Array<ProductCategoryTreePublic>;
    count: number;
};

/**
 * 创建商品分类请求
 */
export type ProductCategoryCreate = {
    /**
     * 分类名称，同一父级下应保持唯一
     */
    name: string;
    /**
     * 为空表示顶级分类
     */
    parent_id?: (string | null);
    /**
     * 分类图标对应的图片资源 UUID
     */
    icon_id?: (string | null);
    /**
     * 数值越小越靠前
     */
    sort?: number;
    is_active?: boolean;
};

/**
 * 商品分类公开响应
 */
export type ProductCategoryPublic = {
    id: string;
    name: string;
    parent_id: (string | null);
    icon_id: (string | null);
    icon_url?: (string | null);
    product_count: number;
    sort: number;
    is_active: boolean;
    created_at?: (string | null);
    updated_at?: (string | null);
};

/**
 * 商品分类树节点响应
 */
export type ProductCategoryTreePublic = {
    id: string;
    name: string;
    parent_id: (string | null);
    icon_id: (string | null);
    icon_url?: (string | null);
    product_count: number;
    sort: number;
    is_active: boolean;
    created_at?: (string | null);
    updated_at?: (string | null);
    /**
     * 按 sort 排序的子分类树节点
     */
    children?: Array<ProductCategoryTreePublic>;
};

/**
 * 更新商品分类请求（全部可选）
 */
export type ProductCategoryUpdate = {
    name?: (string | null);
    parent_id?: (string | null);
    icon_id?: (string | null);
    sort?: (number | null);
    is_active?: (boolean | null);
};

/**
 * 创建商品请求
 */
export type ProductCreate = {
    name: string;
    category_id: string;
    image_id?: (string | null);
    source_type?: SourceType;
    status?: ProductStatus;
    is_closed?: boolean;
    sort?: number;
    type?: ProductType;
    supplier?: (ProductSupplierCreate | null);
    pricing: ProductPricingCreate;
    inventory?: ProductInventoryCreate;
    fulfillment?: ProductFulfillmentCreate;
    buy_params?: Array<ProductBuyParamCreate>;
};

/**
 * 商品履约配置创建请求
 */
export type ProductFulfillmentCreate = {
    fulfillment_type?: RedeemType;
    can_refund?: boolean;
    after_sale_rules?: string;
    description?: string;
    unit?: string;
    input_fields_overridden?: boolean;
    params_template?: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * 商品履约配置公开响应
 */
export type ProductFulfillmentPublic = {
    fulfillment_type: RedeemType;
    can_refund: boolean;
    after_sale_rules: string;
    description: string;
    unit: string;
    input_fields_overridden: boolean;
    params_template: Array<{
        [key: string]: unknown;
    }>;
};

/**
 * 商品履约配置更新请求（全部可选）
 */
export type ProductFulfillmentUpdate = {
    fulfillment_type?: (RedeemType | null);
    can_refund?: (boolean | null);
    after_sale_rules?: (string | null);
    description?: (string | null);
    unit?: (string | null);
    input_fields_overridden?: (boolean | null);
    params_template?: (Array<{
    [key: string]: unknown;
}> | null);
};

/**
 * 商品库存配置创建请求
 */
export type ProductInventoryCreate = {
    min_quantity?: number;
    max_quantity?: number;
    is_repeatable?: boolean;
    is_batch?: boolean;
    purchase_step?: (number | string);
    /**
     * -1 表示无限库存
     */
    stock?: number;
};

/**
 * 商品库存配置公开响应
 */
export type ProductInventoryPublic = {
    min_quantity: number;
    max_quantity: number;
    is_repeatable: boolean;
    is_batch: boolean;
    purchase_step: string;
    stock: number;
};

/**
 * 商品库存配置更新请求（全部可选）
 */
export type ProductInventoryUpdate = {
    min_quantity?: (number | null);
    max_quantity?: (number | null);
    is_repeatable?: (boolean | null);
    is_batch?: (boolean | null);
    purchase_step?: (number | string | null);
    stock?: (number | null);
};

/**
 * 商品价格配置创建请求
 */
export type ProductPricingCreate = {
    /**
     * 关联价格模板的 UUID，与固定价格、商品系数互斥
     */
    price_template_id?: (string | null);
    cost_price?: (number | string);
    loss_price?: (number | string);
    /**
     * 设置后直接作为最终售价，与价格模板、商品独立系数互斥
     */
    fixed_price?: (number | string | null);
    /**
     * 替代模板加价率，与价格模板、固定价格互斥
     */
    item_coefficient?: (number | string | null);
    /**
     * 前端显示价格时保留的小数位数
     */
    price_display_precision?: number;
};

/**
 * 商品价格配置公开响应
 */
export type ProductPricingPublic = {
    price_template_id: (string | null);
    cost_price: string;
    loss_price: string;
    fixed_price: (string | null);
    item_coefficient: (string | null);
    price_display_precision: number;
    rule_type: RuleType;
    config_mode: string;
};

/**
 * 商品价格配置更新请求（全部可选）
 */
export type ProductPricingUpdate = {
    /**
     * 显式传 null 表示清除价格模板
     */
    price_template_id?: (string | null);
    cost_price?: (number | string | null);
    loss_price?: (number | string | null);
    /**
     * 显式传 null 表示清除固定价格
     */
    fixed_price?: (number | string | null);
    /**
     * 显式传 null 表示清除商品独立系数
     */
    item_coefficient?: (number | string | null);
    price_display_precision?: (number | null);
};

/**
 * 商品公开响应
 */
export type ProductPublic = {
    id: string;
    name: string;
    category_id: (string | null);
    category_name?: (string | null);
    image_id?: (string | null);
    image_url?: (string | null);
    source_type: SourceType;
    status: ProductStatus;
    is_closed: boolean;
    sort: number;
    type: ProductType;
    is_active: boolean;
    created_at?: (string | null);
    updated_at?: (string | null);
    supplier?: (ProductSupplierPublic | null);
    pricing?: (ProductPricingPublic | null);
    inventory?: (ProductInventoryPublic | null);
    fulfillment?: (ProductFulfillmentPublic | null);
    buy_params?: Array<ProductBuyParamPublic>;
};

/**
 * 商品列表响应
 */
export type ProductsPublic = {
    data: Array<ProductPublic>;
    count: number;
};

/**
 * 商品状态
 */
export type ProductStatus = 1 | 2 | 3 | 5 | 6 | 7 | 8;

/**
 * 商品货源创建请求
 */
export type ProductSupplierCreate = {
    /**
     * 为空表示未关联供应商
     */
    supplier_id?: (string | null);
    /**
     * 供应商侧的商品 SKU 标识
     */
    sku_id?: (string | null);
};

/**
 * 商品货源公开响应
 */
export type ProductSupplierPublic = {
    supplier_id: (string | null);
    supplier_name?: (string | null);
    sku_id?: (string | null);
};

/**
 * 商品货源更新请求（全部可选）
 */
export type ProductSupplierUpdate = {
    supplier_id?: (string | null);
    sku_id?: (string | null);
};

/**
 * 商品类型
 */
export type ProductType = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;

/**
 * 更新商品请求（全部可选）
 */
export type ProductUpdate = {
    name?: (string | null);
    category_id?: (string | null);
    /**
     * 显式传 null 表示清除商品主图
     */
    image_id?: (string | null);
    source_type?: (SourceType | null);
    status?: (ProductStatus | null);
    is_closed?: (boolean | null);
    sort?: (number | null);
    type?: (ProductType | null);
    is_active?: (boolean | null);
    /**
     * 传 null 表示清除货源记录
     */
    supplier?: (ProductSupplierUpdate | null);
    /**
     * 传 null 将被拒绝，商品必须保留价格配置
     */
    pricing?: (ProductPricingUpdate | null);
    /**
     * 传 null 将被拒绝，商品必须保留库存配置
     */
    inventory?: (ProductInventoryUpdate | null);
    /**
     * 传 null 将被拒绝，商品必须保留履约配置
     */
    fulfillment?: (ProductFulfillmentUpdate | null);
    /**
     * 传 null 表示清空下单参数，传列表表示整体替换
     */
    buy_params?: (Array<ProductBuyParamUpdate> | null);
};

/**
 * 发货方式
 */
export type RedeemType = 1 | 2 | 3;

/**
 * 刷新令牌请求
 */
export type RefreshTokenRequest = {
    refresh_token: string;
};

/**
 * 定价规则（由字段派生，不落库）
 */
export type RuleType = 1 | 2 | 3;

/**
 * 立即执行任务响应
 */
export type RunTaskPublic = {
    task_id: string;
};

/**
 * 创建计划任务请求
 */
export type ScheduleCreate = {
    /**
     * 唯一标识，beat 启动时会按名称同步
     */
    name: string;
    /**
     * Celery 任务完整路径
     */
    task: string;
    schedule_type: ScheduleType;
    /**
     * schedule_type=crontab 时必填
     */
    crontab?: (CrontabScheduleIn | null);
    /**
     * schedule_type=interval 时必填
     */
    interval?: (IntervalScheduleIn | null);
    args?: Array<unknown>;
    kwargs?: {
        [key: string]: unknown;
    };
    enabled?: boolean;
    description?: (string | null);
};

/**
 * 计划任务公开响应
 */
export type SchedulePublic = {
    id: number;
    name: string;
    task: string;
    schedule_type: ScheduleType;
    crontab?: (CrontabSchedulePublic | null);
    interval?: (IntervalSchedulePublic | null);
    /**
     * 如 every 30 minutes 或分时日月周表达式
     */
    schedule_description?: (string | null);
    args: Array<unknown>;
    kwargs: {
        [key: string]: unknown;
    };
    enabled: boolean;
    description?: (string | null);
    last_run_at?: (string | null);
    total_run_count?: number;
    date_changed?: (string | null);
};

/**
 * 计划任务列表响应
 */
export type SchedulesPublic = {
    data: Array<SchedulePublic>;
    count: number;
};

/**
 * 计划任务调度类型
 */
export type ScheduleType = 'crontab' | 'interval';

/**
 * 更新计划任务请求（全部可选）
 */
export type ScheduleUpdate = {
    name?: (string | null);
    task?: (string | null);
    schedule_type?: (ScheduleType | null);
    crontab?: (CrontabScheduleIn | null);
    interval?: (IntervalScheduleIn | null);
    args?: (Array<unknown> | null);
    kwargs?: ({
    [key: string]: unknown;
} | null);
    enabled?: (boolean | null);
    description?: (string | null);
};

/**
 * 设置项（登录用户可读）
 */
export type SettingRead = {
    key: string;
    value: unknown;
    description: (string | null);
    updated_by: (string | null);
    updated_at: (string | null);
};

/**
 * 设置列表响应
 */
export type SettingsRead = {
    data: Array<SettingRead>;
};

/**
 * 更新设置请求
 */
export type SettingUpdate = {
    value: unknown;
};

/**
 * 商品来源
 */
export type SourceType = 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8;

/**
 * 创建供应商请求
 */
export type SupplierCreate = {
    /**
     * 供应商名称标识，全局唯一
     */
    name: string;
    /**
     * 供应商平台标识
     */
    platform: PlatformEnum;
    /**
     * API 请求的基础 URL
     */
    base_url: string;
    /**
     * API 认证密钥 Key
     */
    app_key: string;
    /**
     * API 认证密钥 Secret，响应中脱敏
     */
    app_secret: string;
    /**
     * active=启用中, inactive=已停用, suspended=异常冻结
     */
    status?: string;
    /**
     * online=可达, offline=不可达, unknown=未知
     */
    connection_status?: string;
    /**
     * API 请求超时时间
     */
    timeout_seconds?: number;
    /**
     * 请求失败时的重试次数
     */
    retry_times?: number;
    /**
     * 备注说明
     */
    description?: (string | null);
};

/**
 * 管理员补录供应商订单号请求
 */
export type SupplierOrderIdUpdateRequest = {
    /**
     * 人工确认上游已下单后补录
     */
    supplier_order_id: string;
};

/**
 * 供应商公开响应
 */
export type SupplierPublic = {
    /**
     * 供应商名称标识，全局唯一
     */
    name: string;
    /**
     * 供应商平台标识
     */
    platform: PlatformEnum;
    /**
     * API 请求的基础 URL
     */
    base_url: string;
    /**
     * API 认证密钥 Key
     */
    app_key: string;
    /**
     * API 认证密钥 Secret，响应中脱敏
     */
    app_secret: string;
    /**
     * active=启用中, inactive=已停用, suspended=异常冻结
     */
    status?: string;
    /**
     * online=可达, offline=不可达, unknown=未知
     */
    connection_status?: string;
    /**
     * API 请求超时时间
     */
    timeout_seconds?: number;
    /**
     * 请求失败时的重试次数
     */
    retry_times?: number;
    /**
     * 备注说明
     */
    description?: (string | null);
    id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
    is_active?: boolean;
    balance?: (string | null);
};

/**
 * 供应商列表响应
 */
export type SuppliersPublic = {
    data: Array<SupplierPublic>;
    count: number;
};

/**
 * 更新供应商请求（全部可选，不含 balance）
 */
export type SupplierUpdate = {
    platform?: (PlatformEnum | null);
    name?: (string | null);
    base_url?: (string | null);
    app_key?: (string | null);
    app_secret?: (string | null);
    status?: (string | null);
    connection_status?: (string | null);
    timeout_seconds?: (number | null);
    retry_times?: (number | null);
    description?: (string | null);
};

/**
 * 可选任务项，供前端下拉选择
 */
export type TaskOption = {
    value: string;
    label: string;
    signature?: (string | null);
    doc?: (string | null);
};

/**
 * 任务选项列表响应
 */
export type TaskOptionsPublic = {
    data: Array<TaskOption>;
};

/**
 * Celery 任务状态响应
 */
export type TaskStatusPublic = {
    status: string;
    success?: (boolean | null);
    result?: ({
    [key: string]: unknown;
} | null);
};

/**
 * 访问令牌响应（登录与刷新时返回）
 */
export type Token = {
    access_token: string;
    token_type?: string;
    refresh_token?: (string | null);
};

/**
 * 修改密码请求
 */
export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * 上游商品分类列表响应
 */
export type UpstreamCategoriesPublic = {
    data: Array<UpstreamCategoryPublic>;
};

/**
 * 上游商品分类选项
 */
export type UpstreamCategoryPublic = {
    /**
     * 上游商品分类 ID
     */
    id: string;
    /**
     * 上游商品分类名称
     */
    name: string;
    /**
     * 父分类 ID，0 或空表示顶级分类
     */
    parent_id?: (string | null);
};

/**
 * 上游商品列表项（与本地货源匹配状态）
 */
export type UpstreamProductPublic = {
    /**
     * 上游商品 ID
     */
    upstream_id: string;
    /**
     * 上游商品名称
     */
    name: string;
    /**
     * 上游价格；列表接口可能不返回
     */
    cost_price?: (string | null);
    /**
     * 是否已存在匹配的本地商品货源
     */
    synced?: boolean;
    /**
     * 已同步时对应的本地商品 UUID
     */
    local_product_id?: (string | null);
};

/**
 * 上游商品列表响应
 */
export type UpstreamProductsPublic = {
    data: Array<UpstreamProductPublic>;
    count: number;
};

/**
 * 创建同步任务响应
 */
export type UpstreamProductSyncPublic = {
    task_id: string;
};

/**
 * 提交同步的上游商品 ID 列表
 */
export type UpstreamProductSyncRequest = {
    product_ids: Array<(string)>;
    /**
     * 同步时写入商品的本地分类，不传则保持原分类
     */
    category_id?: (string | null);
};

/**
 * 创建用户请求
 */
export type UserCreate = {
    /**
     * 用户名，不填时默认使用邮箱
     */
    username?: (string | null);
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    can_order?: boolean;
    full_name?: (string | null);
    password: string;
};

/**
 * 用户公开响应
 */
export type UserPublic = {
    username: string;
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    can_order?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

/**
 * 用户注册请求
 */
export type UserRegister = {
    /**
     * 用户名，不填时默认使用邮箱
     */
    username?: (string | null);
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * 用户列表响应
 */
export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

/**
 * 更新用户请求（全部可选）
 */
export type UserUpdate = {
    username?: (string | null);
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    can_order?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

/**
 * 当前用户更新个人信息请求
 */
export type UserUpdateMe = {
    username?: (string | null);
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * 管理员调账请求
 */
export type WalletAdjust = {
    /**
     * 正数入账，负数扣款，不能为 0
     */
    amount: (number | string);
    /**
     * 本次调账的备注说明
     */
    remark: string;
};

/**
 * 钱包公开响应
 */
export type WalletPublic = {
    id: string;
    user_id: string;
    balance: string;
    currency: string;
    created_at?: (string | null);
};

/**
 * 钱包列表响应
 */
export type WalletsPublic = {
    data: Array<WalletPublic>;
    count: number;
};

/**
 * 钱包交易流水公开响应
 */
export type WalletTransactionPublic = {
    id: string;
    wallet_id: string;
    amount: string;
    balance_after: string;
    tx_type: string;
    ref_type?: (string | null);
    ref_id?: (string | null);
    remark?: (string | null);
    operator_id?: (string | null);
    created_at?: (string | null);
};

/**
 * 钱包交易流水列表响应
 */
export type WalletTransactionsPublic = {
    data: Array<WalletTransactionPublic>;
    count: number;
};

export type AutomationReadAutomationTasksData = {
    limit?: number;
    skip?: number;
    status?: (AutomationTaskStatus | null);
};

export type AutomationReadAutomationTasksResponse = (AutomationTasksPublic);

export type AutomationCreateAutomationTaskData = {
    requestBody: AutomationTaskCreate;
};

export type AutomationCreateAutomationTaskResponse = (AutomationTaskPublic);

export type AutomationReadExecutorOptionsResponse = (TaskOptionsPublic);

export type AutomationReadAutomationTaskArchivesData = {
    limit?: number;
    skip?: number;
    status?: (AutomationTaskStatus | null);
};

export type AutomationReadAutomationTaskArchivesResponse = (AutomationTaskArchivesPublic);

export type AutomationReadAutomationTaskData = {
    id: string;
};

export type AutomationReadAutomationTaskResponse = (AutomationTaskPublic);

export type AutomationRetryAutomationTaskData = {
    id: string;
};

export type AutomationRetryAutomationTaskResponse = (AutomationTaskPublic);

export type AutomationCancelAutomationTaskData = {
    id: string;
};

export type AutomationCancelAutomationTaskResponse = (AutomationTaskPublic);

export type AutomationReadAutomationEventsData = {
    eventType?: (string | null);
    limit?: number;
    skip?: number;
};

export type AutomationReadAutomationEventsResponse = (AutomationEventsPublic);

export type AutomationPublishAutomationEventRouteData = {
    requestBody: AutomationEventCreate;
};

export type AutomationPublishAutomationEventRouteResponse = (AutomationEventPublic);

export type AutomationReadAutomationRulesData = {
    limit?: number;
    skip?: number;
};

export type AutomationReadAutomationRulesResponse = (AutomationRulesPublic);

export type AutomationCreateAutomationRuleData = {
    requestBody: AutomationRuleCreate;
};

export type AutomationCreateAutomationRuleResponse = (AutomationRulePublic);

export type AutomationReadAutomationRuleData = {
    id: string;
};

export type AutomationReadAutomationRuleResponse = (AutomationRulePublic);

export type AutomationUpdateAutomationRuleData = {
    id: string;
    requestBody: AutomationRuleUpdate;
};

export type AutomationUpdateAutomationRuleResponse = (AutomationRulePublic);

export type AutomationDeleteAutomationRuleData = {
    id: string;
};

export type AutomationDeleteAutomationRuleResponse = (Message);

export type AutomationToggleAutomationRuleData = {
    id: string;
};

export type AutomationToggleAutomationRuleResponse = (AutomationRulePublic);

export type ImageCategoriesReadCategoriesResponse = (ImageCategoriesPublic);

export type ImageCategoriesCreateNewCategoryData = {
    requestBody: ImageCategoryCreate;
};

export type ImageCategoriesCreateNewCategoryResponse = (ImageCategoryPublic);

export type ImageCategoriesReadCategoryOptionsResponse = (Array<(string)>);

export type ImageCategoriesReadCategoryData = {
    id: string;
};

export type ImageCategoriesReadCategoryResponse = (ImageCategoryPublic);

export type ImageCategoriesUpdateExistingCategoryData = {
    id: string;
    requestBody: ImageCategoryUpdate;
};

export type ImageCategoriesUpdateExistingCategoryResponse = (ImageCategoryPublic);

export type ImageCategoriesDeleteExistingCategoryData = {
    id: string;
};

export type ImageCategoriesDeleteExistingCategoryResponse = (Message);

export type ImagesReadImagesData = {
    /**
     * 按分类筛选：avatar, product, product_detail
     */
    category?: (string | null);
    limit?: number;
    skip?: number;
};

export type ImagesReadImagesResponse = (ImagesPublic);

export type ImagesReadImageData = {
    id: string;
};

export type ImagesReadImageResponse = (ImagePublic);

export type ImagesDeleteImageData = {
    id: string;
};

export type ImagesDeleteImageResponse = (Message);

export type ImagesUpdateImageData = {
    id: string;
    requestBody: ImageUpdate;
};

export type ImagesUpdateImageResponse = (ImagePublic);

export type ImagesUploadImageData = {
    /**
     * 图片分类：avatar, product, product_detail
     */
    category?: (string | null);
    formData: Body_images_upload_image;
};

export type ImagesUploadImageResponse = (ImagePublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LevelsReadLevelsResponse = (LevelsPublic);

export type LevelsReadLevelData = {
    level: number;
};

export type LevelsReadLevelResponse = (LevelPublic);

export type LevelsUpdateLevelEndpointData = {
    level: number;
    requestBody: LevelUpdate;
};

export type LevelsUpdateLevelEndpointResponse = (LevelPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginRefreshTokenData = {
    requestBody: RefreshTokenRequest;
};

export type LoginRefreshTokenResponse = (Token);

export type LoginLogoutData = {
    requestBody: RefreshTokenRequest;
};

export type LoginLogoutResponse = (Message);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type LoginTestTokenResponse = (UserPublic);

export type OrdersCreateUserOrdersData = {
    requestBody: AdminOrdersCreate;
};

export type OrdersCreateUserOrdersResponse = (AdminOrdersPublic);

export type OrdersReadOrdersData = {
    limit?: number;
    paramValue?: (string | null);
    skip?: number;
    status?: (OrderStatus | null);
    userId?: (string | null);
};

export type OrdersReadOrdersResponse = (OrdersPublic);

export type OrdersReadUserOrdersData = {
    limit?: number;
    skip?: number;
};

export type OrdersReadUserOrdersResponse = (OrdersPublic);

export type OrdersCreateAdminOrdersApiData = {
    requestBody: AdminOrdersCreate;
};

export type OrdersCreateAdminOrdersApiResponse = (AdminOrdersPublic);

export type OrdersPreviewAdminOrdersApiData = {
    requestBody: AdminOrdersCreate;
};

export type OrdersPreviewAdminOrdersApiResponse = (AdminOrdersPreviewPublic);

export type OrdersReadUserOrderData = {
    orderId: string;
};

export type OrdersReadUserOrderResponse = (OrderPublic);

export type OrdersCancelUserOrderData = {
    orderId: string;
};

export type OrdersCancelUserOrderResponse = (OrderPublic);

export type OrdersReadOrderData = {
    orderId: string;
};

export type OrdersReadOrderResponse = (OrderPublic);

export type OrdersFulfillOrderApiData = {
    orderId: string;
};

export type OrdersFulfillOrderApiResponse = (OrderPublic);

export type OrdersCancelOrderApiData = {
    orderId: string;
};

export type OrdersCancelOrderApiResponse = (OrderPublic);

export type OrdersRefundOrderApiData = {
    orderId: string;
    requestBody: OrderRefundRequest;
};

export type OrdersRefundOrderApiResponse = (OrderPublic);

export type OrdersUpdateOrderStatusApiData = {
    orderId: string;
    requestBody: OrderStatusUpdateRequest;
};

export type OrdersUpdateOrderStatusApiResponse = (OrderPublic);

export type OrdersSyncOrderStatusApiData = {
    orderId: string;
};

export type OrdersSyncOrderStatusApiResponse = (OrderPublic);

export type OrdersRecordSupplierOrderIdApiData = {
    orderId: string;
    requestBody: SupplierOrderIdUpdateRequest;
};

export type OrdersRecordSupplierOrderIdApiResponse = (OrderPublic);

export type PriceTemplatesReadPriceTemplatesData = {
    limit?: number;
    skip?: number;
};

export type PriceTemplatesReadPriceTemplatesResponse = (PriceTemplatesPublic);

export type PriceTemplatesCreatePriceTemplateData = {
    requestBody: PriceTemplateCreate;
};

export type PriceTemplatesCreatePriceTemplateResponse = (PriceTemplatePublic);

export type PriceTemplatesReadPriceTemplateData = {
    templateId: string;
};

export type PriceTemplatesReadPriceTemplateResponse = (PriceTemplatePublic);

export type PriceTemplatesUpdatePriceTemplateData = {
    requestBody: PriceTemplateUpdate;
    templateId: string;
};

export type PriceTemplatesUpdatePriceTemplateResponse = (PriceTemplatePublic);

export type PriceTemplatesDeletePriceTemplateData = {
    templateId: string;
};

export type PriceTemplatesDeletePriceTemplateResponse = (Message);

export type PrivateCreateUserPrivateData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserPrivateResponse = (UserPublic);

export type ProductCategoriesReadProductCategoriesResponse = (ProductCategoriesPublic);

export type ProductCategoriesCreateProductCategoryData = {
    requestBody: ProductCategoryCreate;
};

export type ProductCategoriesCreateProductCategoryResponse = (ProductCategoryPublic);

export type ProductCategoriesReadProductCategoryData = {
    categoryId: string;
};

export type ProductCategoriesReadProductCategoryResponse = (ProductCategoryPublic);

export type ProductCategoriesUpdateProductCategoryData = {
    categoryId: string;
    requestBody: ProductCategoryUpdate;
};

export type ProductCategoriesUpdateProductCategoryResponse = (ProductCategoryPublic);

export type ProductCategoriesDeleteProductCategoryData = {
    categoryId: string;
};

export type ProductCategoriesDeleteProductCategoryResponse = (Message);

export type ProductsReadProductsData = {
    categoryId?: (string | null);
    isClosed?: (boolean | null);
    limit?: number;
    name?: (string | null);
    productType?: (ProductType | null);
    skip?: number;
    sourceType?: (SourceType | null);
    status?: (ProductStatus | null);
};

export type ProductsReadProductsResponse = (ProductsPublic);

export type ProductsCreateProductData = {
    requestBody: ProductCreate;
};

export type ProductsCreateProductResponse = (ProductPublic);

export type ProductsReadProductData = {
    productId: string;
};

export type ProductsReadProductResponse = (ProductPublic);

export type ProductsUpdateProductData = {
    productId: string;
    requestBody: ProductUpdate;
};

export type ProductsUpdateProductResponse = (ProductPublic);

export type ProductsDeleteProductData = {
    productId: string;
};

export type ProductsDeleteProductResponse = (Message);

export type SchedulesReadSchedulesData = {
    limit?: number;
    skip?: number;
};

export type SchedulesReadSchedulesResponse = (SchedulesPublic);

export type SchedulesCreateScheduleData = {
    requestBody: ScheduleCreate;
};

export type SchedulesCreateScheduleResponse = (SchedulePublic);

export type SchedulesReadTaskOptionsResponse = (TaskOptionsPublic);

export type SchedulesReadScheduleData = {
    id: number;
};

export type SchedulesReadScheduleResponse = (SchedulePublic);

export type SchedulesUpdateScheduleData = {
    id: number;
    requestBody: ScheduleUpdate;
};

export type SchedulesUpdateScheduleResponse = (SchedulePublic);

export type SchedulesDeleteScheduleData = {
    id: number;
};

export type SchedulesDeleteScheduleResponse = (Message);

export type SchedulesToggleScheduleData = {
    id: number;
};

export type SchedulesToggleScheduleResponse = (SchedulePublic);

export type SchedulesRunScheduleData = {
    id: number;
};

export type SchedulesRunScheduleResponse = (RunTaskPublic);

export type SchedulesReadTaskStatusData = {
    taskId: string;
};

export type SchedulesReadTaskStatusResponse = (TaskStatusPublic);

export type SettingsReadSettingsResponse = (SettingsRead);

export type SettingsUpdateSettingEndpointData = {
    key: string;
    requestBody: SettingUpdate;
};

export type SettingsUpdateSettingEndpointResponse = (SettingRead);

export type SuppliersReadSuppliersData = {
    limit?: number;
    skip?: number;
};

export type SuppliersReadSuppliersResponse = (SuppliersPublic);

export type SuppliersCreateSupplierData = {
    requestBody: SupplierCreate;
};

export type SuppliersCreateSupplierResponse = (SupplierPublic);

export type SuppliersGetPlatformOptionsResponse = (PlatformOptionsPublic);

export type SuppliersReadSupplierData = {
    id: string;
};

export type SuppliersReadSupplierResponse = (SupplierPublic);

export type SuppliersUpdateSupplierData = {
    id: string;
    requestBody: SupplierUpdate;
};

export type SuppliersUpdateSupplierResponse = (SupplierPublic);

export type SuppliersDeleteSupplierData = {
    id: string;
};

export type SuppliersDeleteSupplierResponse = (Message);

export type SuppliersReadSupplierBalanceData = {
    id: string;
};

export type SuppliersReadSupplierBalanceResponse = (BalancePublic);

export type SuppliersReadUpstreamProductsData = {
    categoryId?: (string | null);
    id: string;
};

export type SuppliersReadUpstreamProductsResponse = (UpstreamProductsPublic);

export type SuppliersReadUpstreamCategoriesData = {
    id: string;
};

export type SuppliersReadUpstreamCategoriesResponse = (UpstreamCategoriesPublic);

export type SuppliersCreateUpstreamProductsSyncData = {
    id: string;
    requestBody: UpstreamProductSyncRequest;
};

export type SuppliersCreateUpstreamProductsSyncResponse = (UpstreamProductSyncPublic);

export type SuppliersReadUpstreamProductsSyncStatusData = {
    id: string;
    taskId: string;
};

export type SuppliersReadUpstreamProductsSyncStatusResponse = (TaskStatusPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WalletsReadWalletMeResponse = (WalletPublic);

export type WalletsReadWalletTransactionsMeData = {
    limit?: number;
    skip?: number;
    txType?: (string | null);
};

export type WalletsReadWalletTransactionsMeResponse = (WalletTransactionsPublic);

export type WalletsReadWalletsData = {
    limit?: number;
    skip?: number;
};

export type WalletsReadWalletsResponse = (WalletsPublic);

export type WalletsAdjustWalletBalanceData = {
    requestBody: WalletAdjust;
    walletId: string;
};

export type WalletsAdjustWalletBalanceResponse = (WalletTransactionPublic);