// This file is auto-generated by @hey-api/openapi-ts

export type Body_images_upload_image = {
    file: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * 分类列表响应
 */
export type ImageCategoriesPublic = {
    data: Array<ImageCategoryPublic>;
    count: number;
};

/**
 * 创建分类请求
 */
export type ImageCategoryCreate = {
    description?: (string | null);
    sort_order?: number;
    icon?: (string | null);
    /**
     * 小写英文字母开头，仅允许小写字母、数字、下划线
     */
    name: string;
};

/**
 * 分类公开响应
 */
export type ImageCategoryPublic = {
    description?: (string | null);
    sort_order?: number;
    icon?: (string | null);
    id: string;
    name: string;
    is_active: boolean;
    image_count: number;
    created_at?: (string | null);
};

/**
 * 更新分类请求（全部可选）
 */
export type ImageCategoryUpdate = {
    description?: (string | null);
    sort_order?: (number | null);
    icon?: (string | null);
    is_active?: (boolean | null);
};

/**
 * 图片公开响应
 */
export type ImagePublic = {
    filename: string;
    file_size: number;
    width: number;
    height: number;
    category?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
    url: string;
};

/**
 * 图片列表响应
 */
export type ImagesPublic = {
    data: Array<ImagePublic>;
    count: number;
};

/**
 * 更新图片请求
 */
export type ImageUpdate = {
    category?: (string | null);
};

/**
 * 创建物品请求
 */
export type ItemCreate = {
    title: string;
    description?: (string | null);
};

/**
 * 物品公开响应
 */
export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
    image_id?: (string | null);
    image_url?: (string | null);
};

/**
 * 物品列表响应
 */
export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

/**
 * 更新物品请求（全部可选）
 */
export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
    image_id?: (string | null);
};

/**
 * 等级公开响应
 */
export type LevelPublic = {
    /**
     * 等级编号，范围 1～10，固定不可修改
     */
    level: number;
    /**
     * 等级名称，如「练气期」
     */
    name: string;
    description?: (string | null);
    /**
     * 是否为新用户的默认等级
     */
    is_default?: boolean;
    id: string;
};

/**
 * 等级列表响应
 */
export type LevelsPublic = {
    data: Array<LevelPublic>;
    count: number;
};

/**
 * 更新等级请求（全部可选）
 */
export type LevelUpdate = {
    name?: (string | null);
    description?: (string | null);
    is_default?: (boolean | null);
};

/**
 * 通用响应消息
 */
export type Message = {
    message: string;
};

/**
 * 重置密码请求
 */
export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * 供应商平台枚举
 */
export type PlatformEnum = 'ylsup';

/**
 * 平台选项——供前端下拉菜单使用
 */
export type PlatformOption = {
    /**
     * 枚举值，用于表单提交
     */
    value: string;
    /**
     * 展示名称，用于下拉菜单展示
     */
    label: string;
};

/**
 * 平台选项列表响应
 */
export type PlatformOptionsPublic = {
    data: Array<PlatformOption>;
};

/**
 * 内部创建用户请求（仅管理员接口使用）
 */
export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * 余额同步响应
 */
export type SupplierBalancePublic = {
    id: string;
    name: string;
    balance?: (string | null);
    message?: string;
};

/**
 * 创建供应商请求
 */
export type SupplierCreate = {
    /**
     * 供应商平台标识
     */
    platform: PlatformEnum;
    /**
     * 供应商名称标识
     */
    name: string;
    /**
     * API 请求的基础 URL
     */
    base_url: string;
    /**
     * API 认证密钥 Key
     */
    app_key: string;
    /**
     * API 认证密钥 Secret，响应中脱敏
     */
    app_secret: string;
    /**
     * active=启用中, inactive=已停用, suspended=异常冻结
     */
    status?: string;
    /**
     * online=可达, offline=不可达, unknown=未知
     */
    connection_status?: string;
    /**
     * API 请求超时时间
     */
    timeout_seconds?: number;
    /**
     * 请求失败时的重试次数
     */
    retry_times?: number;
    /**
     * 备注说明
     */
    description?: (string | null);
};

/**
 * 供应商公开响应
 */
export type SupplierPublic = {
    /**
     * 供应商平台标识
     */
    platform: PlatformEnum;
    /**
     * 供应商名称标识
     */
    name: string;
    /**
     * API 请求的基础 URL
     */
    base_url: string;
    /**
     * API 认证密钥 Key
     */
    app_key: string;
    /**
     * API 认证密钥 Secret，响应中脱敏
     */
    app_secret: string;
    /**
     * active=启用中, inactive=已停用, suspended=异常冻结
     */
    status?: string;
    /**
     * online=可达, offline=不可达, unknown=未知
     */
    connection_status?: string;
    /**
     * API 请求超时时间
     */
    timeout_seconds?: number;
    /**
     * 请求失败时的重试次数
     */
    retry_times?: number;
    /**
     * 备注说明
     */
    description?: (string | null);
    id: string;
    created_at?: (string | null);
    updated_at?: (string | null);
    is_active?: boolean;
    balance?: (string | null);
};

/**
 * 供应商列表响应
 */
export type SuppliersPublic = {
    data: Array<SupplierPublic>;
    count: number;
};

/**
 * 更新供应商请求（全部可选，不含 balance）
 */
export type SupplierUpdate = {
    platform?: (PlatformEnum | null);
    name?: (string | null);
    base_url?: (string | null);
    app_key?: (string | null);
    app_secret?: (string | null);
    status?: (string | null);
    connection_status?: (string | null);
    timeout_seconds?: (number | null);
    retry_times?: (number | null);
    description?: (string | null);
};

/**
 * 访问令牌响应
 */
export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * 修改密码请求
 */
export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * 创建用户请求
 */
export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

/**
 * 用户公开响应
 */
export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

/**
 * 用户注册请求
 */
export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * 用户列表响应
 */
export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

/**
 * 更新用户请求（全部可选）
 */
export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

/**
 * 当前用户更新个人信息请求
 */
export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ImageCategoriesReadCategoriesResponse = (ImageCategoriesPublic);

export type ImageCategoriesCreateNewCategoryData = {
    requestBody: ImageCategoryCreate;
};

export type ImageCategoriesCreateNewCategoryResponse = (ImageCategoryPublic);

export type ImageCategoriesReadCategoryOptionsResponse = (Array<(string)>);

export type ImageCategoriesReadCategoryData = {
    id: string;
};

export type ImageCategoriesReadCategoryResponse = (ImageCategoryPublic);

export type ImageCategoriesUpdateExistingCategoryData = {
    id: string;
    requestBody: ImageCategoryUpdate;
};

export type ImageCategoriesUpdateExistingCategoryResponse = (ImageCategoryPublic);

export type ImageCategoriesDeleteExistingCategoryData = {
    id: string;
};

export type ImageCategoriesDeleteExistingCategoryResponse = (Message);

export type ImagesReadImagesData = {
    /**
     * 按分类筛选：avatar, product, product_detail
     */
    category?: (string | null);
    limit?: number;
    skip?: number;
};

export type ImagesReadImagesResponse = (ImagesPublic);

export type ImagesReadImageData = {
    id: string;
};

export type ImagesReadImageResponse = (ImagePublic);

export type ImagesDeleteImageData = {
    id: string;
};

export type ImagesDeleteImageResponse = (Message);

export type ImagesUpdateImageData = {
    id: string;
    requestBody: ImageUpdate;
};

export type ImagesUpdateImageResponse = (ImagePublic);

export type ImagesUploadImageData = {
    /**
     * 图片分类：avatar, product, product_detail
     */
    category?: (string | null);
    formData: Body_images_upload_image;
};

export type ImagesUploadImageResponse = (ImagePublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LevelsReadLevelsResponse = (LevelsPublic);

export type LevelsReadLevelData = {
    level: number;
};

export type LevelsReadLevelResponse = (LevelPublic);

export type LevelsUpdateLevelEndpointData = {
    level: number;
    requestBody: LevelUpdate;
};

export type LevelsUpdateLevelEndpointResponse = (LevelPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserPrivateData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserPrivateResponse = (UserPublic);

export type SuppliersReadSuppliersData = {
    limit?: number;
    skip?: number;
};

export type SuppliersReadSuppliersResponse = (SuppliersPublic);

export type SuppliersCreateSupplierData = {
    requestBody: SupplierCreate;
};

export type SuppliersCreateSupplierResponse = (SupplierPublic);

export type SuppliersGetPlatformOptionsResponse = (PlatformOptionsPublic);

export type SuppliersReadSupplierData = {
    id: string;
};

export type SuppliersReadSupplierResponse = (SupplierPublic);

export type SuppliersUpdateSupplierData = {
    id: string;
    requestBody: SupplierUpdate;
};

export type SuppliersUpdateSupplierResponse = (SupplierPublic);

export type SuppliersDeleteSupplierData = {
    id: string;
};

export type SuppliersDeleteSupplierResponse = (Message);

export type SuppliersSyncSupplierBalanceData = {
    id: string;
};

export type SuppliersSyncSupplierBalanceResponse = (SupplierBalancePublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);