// This file is auto-generated by @hey-api/openapi-ts

export type Body_images_upload_image = {
    file: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * 图片公开响应
 */
export type ImagePublic = {
    filename: string;
    file_size: number;
    width: number;
    height: number;
    id: string;
    owner_id: string;
    created_at?: (string | null);
    url: string;
};

/**
 * 图片列表响应
 */
export type ImagesPublic = {
    data: Array<ImagePublic>;
    count: number;
};

/**
 * 创建物品请求
 */
export type ItemCreate = {
    title: string;
    description?: (string | null);
};

/**
 * 物品公开响应
 */
export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
    image_id?: (string | null);
    image_url?: (string | null);
};

/**
 * 物品列表响应
 */
export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

/**
 * 更新物品请求（全部可选）
 */
export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
    image_id?: (string | null);
};

/**
 * 通用响应消息
 */
export type Message = {
    message: string;
};

/**
 * 重置密码请求
 */
export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * 内部创建用户请求（仅管理员接口使用）
 */
export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * 访问令牌响应
 */
export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * 修改密码请求
 */
export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * 创建用户请求
 */
export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

/**
 * 用户公开响应
 */
export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

/**
 * 用户注册请求
 */
export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * 用户列表响应
 */
export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

/**
 * 更新用户请求（全部可选）
 */
export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

/**
 * 当前用户更新个人信息请求
 */
export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ImagesReadImagesData = {
    limit?: number;
    skip?: number;
};

export type ImagesReadImagesResponse = (ImagesPublic);

export type ImagesReadImageData = {
    id: string;
};

export type ImagesReadImageResponse = (ImagePublic);

export type ImagesDeleteImageData = {
    id: string;
};

export type ImagesDeleteImageResponse = (Message);

export type ImagesUploadImageData = {
    formData: Body_images_upload_image;
};

export type ImagesUploadImageResponse = (ImagePublic);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserPrivateData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserPrivateResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);