"""商品模块：商品 API 请求与响应模型"""

from app.modules.product.product.schemas.product import (
    ProductBuyParamCreate,
    ProductBuyParamPublic,
    ProductBuyParamUpdate,
    ProductCreate,
    ProductFulfillmentCreate,
    ProductFulfillmentPublic,
    ProductFulfillmentUpdate,
    ProductInventoryCreate,
    ProductInventoryPublic,
    ProductInventoryUpdate,
    ProductPricingCreate,
    ProductPricingPublic,
    ProductPricingUpdate,
    ProductPublic,
    ProductsPublic,
    ProductSupplierCreate,
    ProductSupplierPublic,
    ProductSupplierUpdate,
    ProductUpdate,
)

__all__ = [
    "ProductBuyParamCreate",
    "ProductBuyParamPublic",
    "ProductBuyParamUpdate",
    "ProductCreate",
    "ProductFulfillmentCreate",
    "ProductFulfillmentPublic",
    "ProductFulfillmentUpdate",
    "ProductInventoryCreate",
    "ProductInventoryPublic",
    "ProductInventoryUpdate",
    "ProductPricingCreate",
    "ProductPricingPublic",
    "ProductPricingUpdate",
    "ProductPublic",
    "ProductsPublic",
    "ProductSupplierCreate",
    "ProductSupplierPublic",
    "ProductSupplierUpdate",
    "ProductUpdate",
]
