"""add price template

Revision ID: 140b4ad63aa0
Revises: 126ad2abbc6d
Create Date: 2026-08-01 15:59:28.734984

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '140b4ad63aa0'
down_revision = '126ad2abbc6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('supplier_base_url_key'), 'supplier', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('supplier_base_url_key'), 'supplier', ['base_url'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
