"""init system

Revision ID: 2b2247f69be5
Revises: 45ebf0f831bb
Create Date: 2026-08-05 00:36:33.196737

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2b2247f69be5'
down_revision = '45ebf0f831bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.create_unique_constraint(None, 'supplier', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supplier', type_='unique')
    op.drop_column('supplier', 'name')
    # ### end Alembic commands ###
