"""init system

Revision ID: 45ebf0f831bb
Revises: 8bd6d5f41ec2
Create Date: 2026-08-05 00:35:35.703404

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '45ebf0f831bb'
down_revision = '8bd6d5f41ec2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('supplier_name_key'), 'supplier', type_='unique')
    op.drop_column('supplier', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supplier', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('supplier_name_key'), 'supplier', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
