"""init system

Revision ID: c04373dddaf3
Revises: 
Create Date: 2026-08-02 11:23:54.461007

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c04373dddaf3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagecategory',
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('image_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imagecategory_is_active'), 'imagecategory', ['is_active'], unique=False)
    op.create_index(op.f('ix_imagecategory_name'), 'imagecategory', ['name'], unique=True)
    op.create_table('price_template',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_template_is_active'), 'price_template', ['is_active'], unique=False)
    op.create_table('supplier',
    sa.Column('platform', sa.Enum('YLSUP', name='platformenum'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('app_key', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('app_secret', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('connection_status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('retry_times', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_supplier_is_active'), 'supplier', ['is_active'], unique=False)
    op.create_table('user_level',
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level')
    )
    op.create_index(op.f('ix_user_level_is_active'), 'user_level', ['is_active'], unique=False)
    op.create_table('price_template_rule',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('price_template_id', sa.Uuid(), nullable=False),
    sa.Column('level_id', sa.Uuid(), nullable=False),
    sa.Column('discount_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['user_level.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['price_template_id'], ['price_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('price_template_id', 'level_id')
    )
    op.create_index(op.f('ix_price_template_rule_is_active'), 'price_template_rule', ['is_active'], unique=False)
    op.create_table('user',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('level_id', sa.Uuid(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['user_level.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_is_active'), 'user', ['is_active'], unique=False)
    op.create_table('image',
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('file_hash', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_category'), 'image', ['category'], unique=False)
    op.create_index(op.f('ix_image_file_hash'), 'image', ['file_hash'], unique=True)
    op.create_index(op.f('ix_image_is_active'), 'image', ['is_active'], unique=False)
    op.create_table('item',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('image_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_is_active'), 'item', ['is_active'], unique=False)
    op.create_table('product_category',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('icon_id', sa.Uuid(), nullable=True),
    sa.Column('product_count', sa.Integer(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['icon_id'], ['image.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['product_category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_category_is_active'), 'product_category', ['is_active'], unique=False)
    op.create_index(op.f('ix_product_category_parent_id'), 'product_category', ['parent_id'], unique=False)
    op.create_table('product',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('image_id', sa.Uuid(), nullable=True),
    sa.Column('source_type', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_category.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_category_id'), 'product', ['category_id'], unique=False)
    op.create_index('ix_product_category_status', 'product', ['category_id', 'status'], unique=False)
    op.create_index(op.f('ix_product_image_id'), 'product', ['image_id'], unique=False)
    op.create_index(op.f('ix_product_is_active'), 'product', ['is_active'], unique=False)
    op.create_index(op.f('ix_product_is_closed'), 'product', ['is_closed'], unique=False)
    op.create_index(op.f('ix_product_sort'), 'product', ['sort'], unique=False)
    op.create_index(op.f('ix_product_source_type'), 'product', ['source_type'], unique=False)
    op.create_index(op.f('ix_product_status'), 'product', ['status'], unique=False)
    op.create_index('ix_product_status_sort', 'product', ['status', 'sort'], unique=False)
    op.create_table('product_buy_param',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('input_type', sa.Integer(), nullable=False),
    sa.Column('type_config', sa.JSON(), nullable=False),
    sa.Column('default_value', sa.Text(), nullable=False),
    sa.Column('use_default', sa.Boolean(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('is_edit', sa.Boolean(), nullable=False),
    sa.Column('validate_min', sa.Integer(), nullable=False),
    sa.Column('validate_max', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'key', name='uq_product_buy_param_product_key')
    )
    op.create_index(op.f('ix_product_buy_param_is_active'), 'product_buy_param', ['is_active'], unique=False)
    op.create_table('product_fulfillment',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('fulfillment_type', sa.Integer(), nullable=False),
    sa.Column('can_refund', sa.Boolean(), nullable=False),
    sa.Column('after_sale_rules', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('input_fields_overridden', sa.Boolean(), nullable=False),
    sa.Column('params_template', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_product_fulfillment_is_active'), 'product_fulfillment', ['is_active'], unique=False)
    op.create_table('product_inventory',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=False),
    sa.Column('max_quantity', sa.Integer(), nullable=False),
    sa.Column('is_repeatable', sa.Boolean(), nullable=False),
    sa.Column('is_batch', sa.Boolean(), nullable=False),
    sa.Column('purchase_step', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.CheckConstraint('min_quantity <= max_quantity', name='ck_product_inventory_min_lte_max'),
    sa.CheckConstraint('stock >= -1', name='ck_product_inventory_stock_gte_minus_one'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_product_inventory_is_active'), 'product_inventory', ['is_active'], unique=False)
    op.create_table('product_pricing',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('price_template_id', sa.Uuid(), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('loss_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fixed_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('item_coefficient', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('price_display_precision', sa.Integer(), nullable=False),
    sa.CheckConstraint('(CASE WHEN price_template_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN fixed_price IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN item_coefficient IS NOT NULL THEN 1 ELSE 0 END) = 1', name='ck_product_pricing_price_rule'),
    sa.ForeignKeyConstraint(['price_template_id'], ['price_template.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_product_pricing_is_active'), 'product_pricing', ['is_active'], unique=False)
    op.create_index(op.f('ix_product_pricing_price_template_id'), 'product_pricing', ['price_template_id'], unique=False)
    op.create_table('product_supplier',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('supplier_id', sa.Uuid(), nullable=True),
    sa.Column('sku_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_index(op.f('ix_product_supplier_is_active'), 'product_supplier', ['is_active'], unique=False)
    op.create_index(op.f('ix_product_supplier_sku_id'), 'product_supplier', ['sku_id'], unique=False)
    op.create_index(op.f('ix_product_supplier_supplier_id'), 'product_supplier', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_supplier_supplier_id'), table_name='product_supplier')
    op.drop_index(op.f('ix_product_supplier_sku_id'), table_name='product_supplier')
    op.drop_index(op.f('ix_product_supplier_is_active'), table_name='product_supplier')
    op.drop_table('product_supplier')
    op.drop_index(op.f('ix_product_pricing_price_template_id'), table_name='product_pricing')
    op.drop_index(op.f('ix_product_pricing_is_active'), table_name='product_pricing')
    op.drop_table('product_pricing')
    op.drop_index(op.f('ix_product_inventory_is_active'), table_name='product_inventory')
    op.drop_table('product_inventory')
    op.drop_index(op.f('ix_product_fulfillment_is_active'), table_name='product_fulfillment')
    op.drop_table('product_fulfillment')
    op.drop_index(op.f('ix_product_buy_param_is_active'), table_name='product_buy_param')
    op.drop_table('product_buy_param')
    op.drop_index('ix_product_status_sort', table_name='product')
    op.drop_index(op.f('ix_product_status'), table_name='product')
    op.drop_index(op.f('ix_product_source_type'), table_name='product')
    op.drop_index(op.f('ix_product_sort'), table_name='product')
    op.drop_index(op.f('ix_product_is_closed'), table_name='product')
    op.drop_index(op.f('ix_product_is_active'), table_name='product')
    op.drop_index(op.f('ix_product_image_id'), table_name='product')
    op.drop_index('ix_product_category_status', table_name='product')
    op.drop_index(op.f('ix_product_category_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_product_category_parent_id'), table_name='product_category')
    op.drop_index(op.f('ix_product_category_is_active'), table_name='product_category')
    op.drop_table('product_category')
    op.drop_index(op.f('ix_item_is_active'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_image_is_active'), table_name='image')
    op.drop_index(op.f('ix_image_file_hash'), table_name='image')
    op.drop_index(op.f('ix_image_category'), table_name='image')
    op.drop_table('image')
    op.drop_index(op.f('ix_user_is_active'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_price_template_rule_is_active'), table_name='price_template_rule')
    op.drop_table('price_template_rule')
    op.drop_index(op.f('ix_user_level_is_active'), table_name='user_level')
    op.drop_table('user_level')
    op.drop_index(op.f('ix_supplier_is_active'), table_name='supplier')
    op.drop_table('supplier')
    op.drop_index(op.f('ix_price_template_is_active'), table_name='price_template')
    op.drop_table('price_template')
    op.drop_index(op.f('ix_imagecategory_name'), table_name='imagecategory')
    op.drop_index(op.f('ix_imagecategory_is_active'), table_name='imagecategory')
    op.drop_table('imagecategory')
    # ### end Alembic commands ###
