"""add wallet tables

Revision ID: c9a81ef7a052
Revises: bc51b44c5799
Create Date: 2026-08-02 13:53:03.974827

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c9a81ef7a052'
down_revision = 'bc51b44c5799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(length=3), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_is_active'), 'wallet', ['is_active'], unique=False)
    op.create_index(op.f('ix_wallet_user_id'), 'wallet', ['user_id'], unique=True)
    op.create_table('wallettransaction',
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('wallet_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('tx_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('ref_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('ref_id', sa.Uuid(), nullable=True),
    sa.Column('remark', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('operator_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallettransaction_is_active'), 'wallettransaction', ['is_active'], unique=False)
    op.create_index(op.f('ix_wallettransaction_tx_type'), 'wallettransaction', ['tx_type'], unique=False)
    op.create_index(op.f('ix_wallettransaction_wallet_id'), 'wallettransaction', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallettransaction_wallet_id'), table_name='wallettransaction')
    op.drop_index(op.f('ix_wallettransaction_tx_type'), table_name='wallettransaction')
    op.drop_index(op.f('ix_wallettransaction_is_active'), table_name='wallettransaction')
    op.drop_table('wallettransaction')
    op.drop_index(op.f('ix_wallet_user_id'), table_name='wallet')
    op.drop_index(op.f('ix_wallet_is_active'), table_name='wallet')
    op.drop_table('wallet')
    # ### end Alembic commands ###
