/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSuppliersRouteImport } from './routes/_layout/suppliers'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutPriceTemplatesRouteImport } from './routes/_layout/price-templates'
import { Route as LayoutLevelsRouteImport } from './routes/_layout/levels'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutImagesRouteImport } from './routes/_layout/images'
import { Route as LayoutCategoriesRouteImport } from './routes/_layout/categories'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSuppliersRoute = LayoutSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPriceTemplatesRoute = LayoutPriceTemplatesRouteImport.update({
  id: '/price-templates',
  path: '/price-templates',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLevelsRoute = LayoutLevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutImagesRoute = LayoutImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCategoriesRoute = LayoutCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/categories': typeof LayoutCategoriesRoute
  '/images': typeof LayoutImagesRoute
  '/items': typeof LayoutItemsRoute
  '/levels': typeof LayoutLevelsRoute
  '/price-templates': typeof LayoutPriceTemplatesRoute
  '/settings': typeof LayoutSettingsRoute
  '/suppliers': typeof LayoutSuppliersRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/categories': typeof LayoutCategoriesRoute
  '/images': typeof LayoutImagesRoute
  '/items': typeof LayoutItemsRoute
  '/levels': typeof LayoutLevelsRoute
  '/price-templates': typeof LayoutPriceTemplatesRoute
  '/settings': typeof LayoutSettingsRoute
  '/suppliers': typeof LayoutSuppliersRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/categories': typeof LayoutCategoriesRoute
  '/_layout/images': typeof LayoutImagesRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/levels': typeof LayoutLevelsRoute
  '/_layout/price-templates': typeof LayoutPriceTemplatesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/suppliers': typeof LayoutSuppliersRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/categories'
    | '/images'
    | '/items'
    | '/levels'
    | '/price-templates'
    | '/settings'
    | '/suppliers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/categories'
    | '/images'
    | '/items'
    | '/levels'
    | '/price-templates'
    | '/settings'
    | '/suppliers'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/categories'
    | '/_layout/images'
    | '/_layout/items'
    | '/_layout/levels'
    | '/_layout/price-templates'
    | '/_layout/settings'
    | '/_layout/suppliers'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/suppliers': {
      id: '/_layout/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof LayoutSuppliersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/price-templates': {
      id: '/_layout/price-templates'
      path: '/price-templates'
      fullPath: '/price-templates'
      preLoaderRoute: typeof LayoutPriceTemplatesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/levels': {
      id: '/_layout/levels'
      path: '/levels'
      fullPath: '/levels'
      preLoaderRoute: typeof LayoutLevelsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/images': {
      id: '/_layout/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof LayoutImagesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/categories': {
      id: '/_layout/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof LayoutCategoriesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutCategoriesRoute: typeof LayoutCategoriesRoute
  LayoutImagesRoute: typeof LayoutImagesRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutLevelsRoute: typeof LayoutLevelsRoute
  LayoutPriceTemplatesRoute: typeof LayoutPriceTemplatesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSuppliersRoute: typeof LayoutSuppliersRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutCategoriesRoute: LayoutCategoriesRoute,
  LayoutImagesRoute: LayoutImagesRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutLevelsRoute: LayoutLevelsRoute,
  LayoutPriceTemplatesRoute: LayoutPriceTemplatesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSuppliersRoute: LayoutSuppliersRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
