/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSuppliersRouteImport } from './routes/_layout/suppliers'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutSchedulesRouteImport } from './routes/_layout/schedules'
import { Route as LayoutProductsRouteImport } from './routes/_layout/products'
import { Route as LayoutProductCategoriesRouteImport } from './routes/_layout/product-categories'
import { Route as LayoutPriceTemplatesRouteImport } from './routes/_layout/price-templates'
import { Route as LayoutOrdersRouteImport } from './routes/_layout/orders'
import { Route as LayoutNotificationsRouteImport } from './routes/_layout/notifications'
import { Route as LayoutLevelsRouteImport } from './routes/_layout/levels'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutImagesRouteImport } from './routes/_layout/images'
import { Route as LayoutGlobalSettingsRouteImport } from './routes/_layout/global-settings'
import { Route as LayoutCategoriesRouteImport } from './routes/_layout/categories'
import { Route as LayoutAutomationRouteImport } from './routes/_layout/automation'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutAutomationIndexRouteImport } from './routes/_layout/automation/index'
import { Route as LayoutAutomationTasksRouteImport } from './routes/_layout/automation/tasks'
import { Route as LayoutAutomationRulesRouteImport } from './routes/_layout/automation/rules'
import { Route as LayoutAutomationEventsRouteImport } from './routes/_layout/automation/events'
import { Route as LayoutAutomationArchivesRouteImport } from './routes/_layout/automation/archives'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSuppliersRoute = LayoutSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSchedulesRoute = LayoutSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductsRoute = LayoutProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductCategoriesRoute = LayoutProductCategoriesRouteImport.update({
  id: '/product-categories',
  path: '/product-categories',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPriceTemplatesRoute = LayoutPriceTemplatesRouteImport.update({
  id: '/price-templates',
  path: '/price-templates',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOrdersRoute = LayoutOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutNotificationsRoute = LayoutNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLevelsRoute = LayoutLevelsRouteImport.update({
  id: '/levels',
  path: '/levels',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutImagesRoute = LayoutImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGlobalSettingsRoute = LayoutGlobalSettingsRouteImport.update({
  id: '/global-settings',
  path: '/global-settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCategoriesRoute = LayoutCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAutomationRoute = LayoutAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAutomationIndexRoute = LayoutAutomationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutAutomationRoute,
} as any)
const LayoutAutomationTasksRoute = LayoutAutomationTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => LayoutAutomationRoute,
} as any)
const LayoutAutomationRulesRoute = LayoutAutomationRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => LayoutAutomationRoute,
} as any)
const LayoutAutomationEventsRoute = LayoutAutomationEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => LayoutAutomationRoute,
} as any)
const LayoutAutomationArchivesRoute =
  LayoutAutomationArchivesRouteImport.update({
    id: '/archives',
    path: '/archives',
    getParentRoute: () => LayoutAutomationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/automation': typeof LayoutAutomationRouteWithChildren
  '/categories': typeof LayoutCategoriesRoute
  '/global-settings': typeof LayoutGlobalSettingsRoute
  '/images': typeof LayoutImagesRoute
  '/items': typeof LayoutItemsRoute
  '/levels': typeof LayoutLevelsRoute
  '/notifications': typeof LayoutNotificationsRoute
  '/orders': typeof LayoutOrdersRoute
  '/price-templates': typeof LayoutPriceTemplatesRoute
  '/product-categories': typeof LayoutProductCategoriesRoute
  '/products': typeof LayoutProductsRoute
  '/schedules': typeof LayoutSchedulesRoute
  '/settings': typeof LayoutSettingsRoute
  '/suppliers': typeof LayoutSuppliersRoute
  '/automation/archives': typeof LayoutAutomationArchivesRoute
  '/automation/events': typeof LayoutAutomationEventsRoute
  '/automation/rules': typeof LayoutAutomationRulesRoute
  '/automation/tasks': typeof LayoutAutomationTasksRoute
  '/automation/': typeof LayoutAutomationIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/categories': typeof LayoutCategoriesRoute
  '/global-settings': typeof LayoutGlobalSettingsRoute
  '/images': typeof LayoutImagesRoute
  '/items': typeof LayoutItemsRoute
  '/levels': typeof LayoutLevelsRoute
  '/notifications': typeof LayoutNotificationsRoute
  '/orders': typeof LayoutOrdersRoute
  '/price-templates': typeof LayoutPriceTemplatesRoute
  '/product-categories': typeof LayoutProductCategoriesRoute
  '/products': typeof LayoutProductsRoute
  '/schedules': typeof LayoutSchedulesRoute
  '/settings': typeof LayoutSettingsRoute
  '/suppliers': typeof LayoutSuppliersRoute
  '/': typeof LayoutIndexRoute
  '/automation/archives': typeof LayoutAutomationArchivesRoute
  '/automation/events': typeof LayoutAutomationEventsRoute
  '/automation/rules': typeof LayoutAutomationRulesRoute
  '/automation/tasks': typeof LayoutAutomationTasksRoute
  '/automation': typeof LayoutAutomationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/automation': typeof LayoutAutomationRouteWithChildren
  '/_layout/categories': typeof LayoutCategoriesRoute
  '/_layout/global-settings': typeof LayoutGlobalSettingsRoute
  '/_layout/images': typeof LayoutImagesRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/levels': typeof LayoutLevelsRoute
  '/_layout/notifications': typeof LayoutNotificationsRoute
  '/_layout/orders': typeof LayoutOrdersRoute
  '/_layout/price-templates': typeof LayoutPriceTemplatesRoute
  '/_layout/product-categories': typeof LayoutProductCategoriesRoute
  '/_layout/products': typeof LayoutProductsRoute
  '/_layout/schedules': typeof LayoutSchedulesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/suppliers': typeof LayoutSuppliersRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/automation/archives': typeof LayoutAutomationArchivesRoute
  '/_layout/automation/events': typeof LayoutAutomationEventsRoute
  '/_layout/automation/rules': typeof LayoutAutomationRulesRoute
  '/_layout/automation/tasks': typeof LayoutAutomationTasksRoute
  '/_layout/automation/': typeof LayoutAutomationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/automation'
    | '/categories'
    | '/global-settings'
    | '/images'
    | '/items'
    | '/levels'
    | '/notifications'
    | '/orders'
    | '/price-templates'
    | '/product-categories'
    | '/products'
    | '/schedules'
    | '/settings'
    | '/suppliers'
    | '/automation/archives'
    | '/automation/events'
    | '/automation/rules'
    | '/automation/tasks'
    | '/automation/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/categories'
    | '/global-settings'
    | '/images'
    | '/items'
    | '/levels'
    | '/notifications'
    | '/orders'
    | '/price-templates'
    | '/product-categories'
    | '/products'
    | '/schedules'
    | '/settings'
    | '/suppliers'
    | '/'
    | '/automation/archives'
    | '/automation/events'
    | '/automation/rules'
    | '/automation/tasks'
    | '/automation'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/automation'
    | '/_layout/categories'
    | '/_layout/global-settings'
    | '/_layout/images'
    | '/_layout/items'
    | '/_layout/levels'
    | '/_layout/notifications'
    | '/_layout/orders'
    | '/_layout/price-templates'
    | '/_layout/product-categories'
    | '/_layout/products'
    | '/_layout/schedules'
    | '/_layout/settings'
    | '/_layout/suppliers'
    | '/_layout/'
    | '/_layout/automation/archives'
    | '/_layout/automation/events'
    | '/_layout/automation/rules'
    | '/_layout/automation/tasks'
    | '/_layout/automation/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/suppliers': {
      id: '/_layout/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof LayoutSuppliersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/schedules': {
      id: '/_layout/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof LayoutSchedulesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/products': {
      id: '/_layout/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof LayoutProductsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/product-categories': {
      id: '/_layout/product-categories'
      path: '/product-categories'
      fullPath: '/product-categories'
      preLoaderRoute: typeof LayoutProductCategoriesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/price-templates': {
      id: '/_layout/price-templates'
      path: '/price-templates'
      fullPath: '/price-templates'
      preLoaderRoute: typeof LayoutPriceTemplatesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/orders': {
      id: '/_layout/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof LayoutOrdersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/notifications': {
      id: '/_layout/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof LayoutNotificationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/levels': {
      id: '/_layout/levels'
      path: '/levels'
      fullPath: '/levels'
      preLoaderRoute: typeof LayoutLevelsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/images': {
      id: '/_layout/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof LayoutImagesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/global-settings': {
      id: '/_layout/global-settings'
      path: '/global-settings'
      fullPath: '/global-settings'
      preLoaderRoute: typeof LayoutGlobalSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/categories': {
      id: '/_layout/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof LayoutCategoriesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/automation': {
      id: '/_layout/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof LayoutAutomationRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/automation/': {
      id: '/_layout/automation/'
      path: '/'
      fullPath: '/automation/'
      preLoaderRoute: typeof LayoutAutomationIndexRouteImport
      parentRoute: typeof LayoutAutomationRoute
    }
    '/_layout/automation/tasks': {
      id: '/_layout/automation/tasks'
      path: '/tasks'
      fullPath: '/automation/tasks'
      preLoaderRoute: typeof LayoutAutomationTasksRouteImport
      parentRoute: typeof LayoutAutomationRoute
    }
    '/_layout/automation/rules': {
      id: '/_layout/automation/rules'
      path: '/rules'
      fullPath: '/automation/rules'
      preLoaderRoute: typeof LayoutAutomationRulesRouteImport
      parentRoute: typeof LayoutAutomationRoute
    }
    '/_layout/automation/events': {
      id: '/_layout/automation/events'
      path: '/events'
      fullPath: '/automation/events'
      preLoaderRoute: typeof LayoutAutomationEventsRouteImport
      parentRoute: typeof LayoutAutomationRoute
    }
    '/_layout/automation/archives': {
      id: '/_layout/automation/archives'
      path: '/archives'
      fullPath: '/automation/archives'
      preLoaderRoute: typeof LayoutAutomationArchivesRouteImport
      parentRoute: typeof LayoutAutomationRoute
    }
  }
}

interface LayoutAutomationRouteChildren {
  LayoutAutomationArchivesRoute: typeof LayoutAutomationArchivesRoute
  LayoutAutomationEventsRoute: typeof LayoutAutomationEventsRoute
  LayoutAutomationRulesRoute: typeof LayoutAutomationRulesRoute
  LayoutAutomationTasksRoute: typeof LayoutAutomationTasksRoute
  LayoutAutomationIndexRoute: typeof LayoutAutomationIndexRoute
}

const LayoutAutomationRouteChildren: LayoutAutomationRouteChildren = {
  LayoutAutomationArchivesRoute: LayoutAutomationArchivesRoute,
  LayoutAutomationEventsRoute: LayoutAutomationEventsRoute,
  LayoutAutomationRulesRoute: LayoutAutomationRulesRoute,
  LayoutAutomationTasksRoute: LayoutAutomationTasksRoute,
  LayoutAutomationIndexRoute: LayoutAutomationIndexRoute,
}

const LayoutAutomationRouteWithChildren =
  LayoutAutomationRoute._addFileChildren(LayoutAutomationRouteChildren)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAutomationRoute: typeof LayoutAutomationRouteWithChildren
  LayoutCategoriesRoute: typeof LayoutCategoriesRoute
  LayoutGlobalSettingsRoute: typeof LayoutGlobalSettingsRoute
  LayoutImagesRoute: typeof LayoutImagesRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutLevelsRoute: typeof LayoutLevelsRoute
  LayoutNotificationsRoute: typeof LayoutNotificationsRoute
  LayoutOrdersRoute: typeof LayoutOrdersRoute
  LayoutPriceTemplatesRoute: typeof LayoutPriceTemplatesRoute
  LayoutProductCategoriesRoute: typeof LayoutProductCategoriesRoute
  LayoutProductsRoute: typeof LayoutProductsRoute
  LayoutSchedulesRoute: typeof LayoutSchedulesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSuppliersRoute: typeof LayoutSuppliersRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAutomationRoute: LayoutAutomationRouteWithChildren,
  LayoutCategoriesRoute: LayoutCategoriesRoute,
  LayoutGlobalSettingsRoute: LayoutGlobalSettingsRoute,
  LayoutImagesRoute: LayoutImagesRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutLevelsRoute: LayoutLevelsRoute,
  LayoutNotificationsRoute: LayoutNotificationsRoute,
  LayoutOrdersRoute: LayoutOrdersRoute,
  LayoutPriceTemplatesRoute: LayoutPriceTemplatesRoute,
  LayoutProductCategoriesRoute: LayoutProductCategoriesRoute,
  LayoutProductsRoute: LayoutProductsRoute,
  LayoutSchedulesRoute: LayoutSchedulesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSuppliersRoute: LayoutSuppliersRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
