"""自动化模块：API 请求与响应模型"""

from app.modules.automation.schemas.automation import (
    AutomationEventCreate,
    AutomationEventPublic,
    AutomationEventsPublic,
    AutomationRuleCreate,
    AutomationRulePublic,
    AutomationRulesPublic,
    AutomationRuleUpdate,
    AutomationTaskArchivePublic,
    AutomationTaskArchivesPublic,
    AutomationTaskCreate,
    AutomationTaskPublic,
    AutomationTasksPublic,
)
from app.modules.automation.schemas.schedule import (
    CrontabScheduleIn,
    CrontabSchedulePublic,
    IntervalScheduleIn,
    IntervalSchedulePublic,
    RunTaskPublic,
    ScheduleBase,
    ScheduleCreate,
    SchedulePublic,
    SchedulesPublic,
    ScheduleUpdate,
    TaskOption,
    TaskOptionsPublic,
    TaskStatusPublic,
)

__all__ = [
    "AutomationEventCreate",
    "AutomationEventPublic",
    "AutomationEventsPublic",
    "AutomationRuleCreate",
    "AutomationRulePublic",
    "AutomationRulesPublic",
    "AutomationRuleUpdate",
    "AutomationTaskArchivePublic",
    "AutomationTaskArchivesPublic",
    "AutomationTaskCreate",
    "AutomationTaskPublic",
    "AutomationTasksPublic",
    "CrontabScheduleIn",
    "CrontabSchedulePublic",
    "IntervalScheduleIn",
    "IntervalSchedulePublic",
    "RunTaskPublic",
    "ScheduleBase",
    "ScheduleCreate",
    "SchedulePublic",
    "SchedulesPublic",
    "ScheduleUpdate",
    "TaskOption",
    "TaskOptionsPublic",
    "TaskStatusPublic",
]
